### ISSUE TITLE
Game crashes: AttributeError: 'Game' object has no attribute 'output'

### ISSUE THREAD

**Issue by royseto** [gever/bwx-adventure#22]
Testcase: https://gist.github.com/royseto/66ac235c5beb24f95db6

**Comment by mcapraro** [comment]
hey there @royseto , there was this function as part of the Game() object:
```
def output(self, text, message_type = 0):
    # we add a newline to user output since they may not add it themselves
    output(text + "\n", message_type)
```
but it was lost in a merge that came after my last check-in. since @jplevyak mentioned merging World and Game, it might be a good time to throw it into the World object since that call to update in bwx-game.py will need to change slighty too. i wont get to this tonight, but if @jplevyak is handling the cleanup of Game + World, it would be good to sneak in this fix too

**Comment by royseto** [comment]
@mcapraro thank you for the pointer.

@jplevyak I went ahead and fixed this now since it causes crashing in game navigation. Feel free to update it appropriately in your refactor of Game + World.
